#ifndef CONFIG_H
#define CONFIG_H

//#define SIMPLE_VERSION "@SIMPLE_VERSION@"
#define PACKAGE_STRING "@PACKAGE_STRING@"
#define PROJECT_NAME "@PROJECT_NAME@"
#define VERSION "@VERSION@"

#endif // CONFIG_H
